app:
  localePath: "src/main/resources/"
spring:
  jackson:
    default-property-inclusion: non_null
  main:
    lazy-initialization: true

spotify:
  client: @spotify.client@
  secret: @spotify.secret@
  redirectUrl: "http://localhost:${server.port}"
  scope:
    - user-read-private
    - user-read-email
    - playlist-read-private
    - playlist-read-collaborative
    - playlist-modify-public
    - playlist-modify-private

server:
  error:
    include-message: always
  port: 3000